// Generated by scripts/generate-theme-tokens.mjs. Do not edit by hand.
import SwiftUI

enum GeneratedThemeTokens {
    struct ColorSet: Sendable {
        let accent: String
        let accentHover: String
        let accentPressed: String
        let accentRing: String
        let accentSubtle: String
        let amber: String
        let assistantBubble: String
        let canvas: String
        let error: String
        let hairline: String
        let hairlineSoft: String
        let onAccent: String
        let success: String
        let surface: String
        let surfaceElevated: String
        let surfaceMuted: String
        let surfaceSoft: String
        let teal: String
        let textMuted: String
        let textPrimary: String
        let textSecondary: String
        let toolBubble: String
        let userBubble: String
        let warning: String
    }

    struct Spacing: Sendable {
        let lg: CGFloat
        let md: CGFloat
        let section: CGFloat
        let sm: CGFloat
        let xl: CGFloat
        let xs: CGFloat
        let xxl: CGFloat
        let xxs: CGFloat
    }

    struct Radius: Sendable {
        let bubble: CGFloat
        let lg: CGFloat
        let md: CGFloat
        let pill: CGFloat
        let sm: CGFloat
        let xl: CGFloat
        let xs: CGFloat
    }

    struct Typography: Sendable {
        let displayFamily: String
        let bodyFamily: String
        let codeFamily: String
        let titleSize: CGFloat
        let bodySize: CGFloat
        let captionSize: CGFloat
        let promptInputSize: CGFloat
    }

    struct Animation: Sendable {
        let springDuration: Double
        let springBounce: Double
        let highlightDuration: Double
    }

    static let light = ColorSet(
        accent: "#cc785c",
        accentHover: "#a9583e",
        accentPressed: "#8f4731",
        accentRing: "rgba(204, 120, 92, 0.28)",
        accentSubtle: "rgba(204, 120, 92, 0.14)",
        amber: "#e8a55a",
        assistantBubble: "transparent",
        canvas: "#faf9f5",
        error: "#c64545",
        hairline: "#e6dfd8",
        hairlineSoft: "#ebe6df",
        onAccent: "#ffffff",
        success: "#5db872",
        surface: "#efe9de",
        surfaceElevated: "#ffffff",
        surfaceMuted: "#e8e0d2",
        surfaceSoft: "#f5f0e8",
        teal: "#5db8a6",
        textMuted: "#8e8b82",
        textPrimary: "#141413",
        textSecondary: "#6c6a64",
        toolBubble: "#f3eee6",
        userBubble: "#f5e7de",
        warning: "#d4a017"
    )

    static let dark = ColorSet(
        accent: "#cc785c",
        accentHover: "#e09880",
        accentPressed: "#a9583e",
        accentRing: "rgba(204, 120, 92, 0.36)",
        accentSubtle: "rgba(204, 120, 92, 0.18)",
        amber: "#e8a55a",
        assistantBubble: "transparent",
        canvas: "#2a2522",
        error: "#c64545",
        hairline: "#3e3833",
        hairlineSoft: "#342f2a",
        onAccent: "#1a1614",
        success: "#5db872",
        surface: "#211e1b",
        surfaceElevated: "#3a3530",
        surfaceMuted: "#342f2a",
        surfaceSoft: "#262320",
        teal: "#5db8a6",
        textMuted: "#8e8b82",
        textPrimary: "#efe9de",
        textSecondary: "#b8b2a7",
        toolBubble: "#211e1b",
        userBubble: "#3a3530",
        warning: "#d4a017"
    )

    static let spacing = Spacing(
        lg: 24,
        md: 16,
        section: 96,
        sm: 12,
        xl: 32,
        xs: 8,
        xxl: 48,
        xxs: 4
    )

    static let radius = Radius(
        bubble: 12,
        lg: 12,
        md: 8,
        pill: 24,
        sm: 6,
        xl: 16,
        xs: 4
    )

    static let typography = Typography(
        displayFamily: "\"Tiempos Headline\", \"Cormorant Garamond\", \"EB Garamond\", Garamond, \"Times New Roman\", serif",
        bodyFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif",
        codeFamily: "\"JetBrains Mono\", ui-monospace, SFMono-Regular, Menlo, monospace",
        titleSize: 18,
        bodySize: 15,
        captionSize: 13,
        promptInputSize: 16
    )

    static let animation = Animation(
        springDuration: 0.35,
        springBounce: 0.2,
        highlightDuration: 0.15
    )
}
